### ISSUE TITLE
no access to create a branch in the githubteacher repository. do I need to be added as a contributor?

### ISSUE THREAD

**Issue by kmarchen1** [githubteacher/developers-jun-2016-americas#133]

**Comment by githubteacher** [comment]
Yes - to do so please comment here: #2

**Comment by hectorsector** [comment]
@kmarchen1 it looks like you were added, so I'll close out this issue but please feel free to open a new one or join us on Gitter if you have any more questions https://gitter.im/githubteacher/developers-jun-2016-americas
